### ISSUE TITLE
torch.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by xiexieren** [yiyuzhuang/IDOL#11]
Hello! When testing demo_data on a 4090 GPU, an OOM error occurs. The specific error is as follows: 
```
(idol) (base) taizun@taizun-Z790-AORUS-ELITE-AX:/mnt/data/code/nerf_data/IDOL$ python run_demo.py --render_mode reconstruct
/mnt/data/code/nerf_data/IDOL/lib/ops/activation.py:10: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)  # cast to float32
/mnt/data/code/nerf_data/IDOL/lib/ops/activation.py:18: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, g):
lib.SapiensGS_SA_v1
lib.models.decoders.UVNDecoder_gender
!!!!!!!!!!!!!!!!!!! cur points number are 200800 !!!!!!!!!!!!!!!!!!!
lib.models.sapiens.SapiensWrapper_ts
======== Freezing DinoWrapper ========
lib.models.transformer_sa.neck_SA_v3_skip
/home/taizun/anaconda3/envs/idol/lib/python3.10/site-packages/torchmetrics/functional/image/lpips.py:326: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(model_path, map_location="cpu"), strict=False)
moving encoder to bf16
lib.models.decoders.UVNDecoder_gender
!!!!!!!!!!!!!!!!!!! cur points number are 200800 !!!!!!!!!!!!!!!!!!!
lib.models.sapiens.SapiensWrapper_ts
======== Freezing DinoWrapper ========
lib.models.transformer_sa.neck_SA_v3_skip
output_folders为: {'image': 'outputs/idol_v0/images', 'video': 'outputs/idol_v0', 'ref': 'outputs/idol_v0'}
  0%|                                                                               | 0/1 [00:00<?, ?it/s]Processing: work_dirs/demo_data/4.jpg
 '''ending ---  invert the root angles'''
Processing: outputs/idol_v0/4.jpg
modify the render images's resolution into 1595x1080
  0%|                                                                              | 0/12 [00:00<?, ?it/s]
  0%|                                                                               | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/data/code/nerf_data/IDOL/run_demo.py", line 296, in <module>
    main()
  File "/mnt/data/code/nerf_data/IDOL/run_demo.py", line 285, in main
    image_plist = process_data_on_gpu(
  File "/mnt/data/code/nerf_data/IDOL/run_demo.py", line 215, in process_data_on_gpu
    res_uv = model.decoder._decode_feature(code_bt) # Decouple UV attributes
  File "/mnt/data/code/nerf_data/IDOL/lib/models/decoders/uvmaps_decoder_gender.py", line 324, in _decode_feature
    rgbs_radius_rot = self.color_net(color_in)
  File "/home/taizun/anaconda3/envs/idol/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/taizun/anaconda3/envs/idol/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/taizun/anaconda3/envs/idol/lib/python3.10/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/taizun/anaconda3/envs/idol/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/taizun/anaconda3/envs/idol/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/taizun/anaconda3/envs/idol/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 176, in forward
    return F.batch_norm(
  File "/home/taizun/anaconda3/envs/idol/lib/python3.10/site-packages/torch/nn/functional.py", line 2512, in batch_norm
    return torch.batch_norm(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 5.62 GiB. GPU 0 has a total capacity of 23.65 GiB of which 2.51 GiB is free. Including non-PyTorch memory, this process has 19.38 GiB memory in use. Of the allocated memory 18.82 GiB is allocated by PyTorch, and 105.46 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
So, does this model require more than 24GB of GPU memory?

**Comment by yiyuzhuang** [comment]
Perhaps you could try setting num_imgs_batch to 1 instead of 5 (in run_demo.py line 200). The issue may be due to the batch size for rendering being too large.

**Comment by xiexieren** [comment]
Thank you very much! Your answer solved my problem!
